---
apiVersion: v1
kind: Pod
metadata:
  name: app-wl03
spec:
  containers:
  - name: monitor-tool
    image: ubuntu
    args:
    - "sleep"
    - "5000"
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 100Mi

