---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-wl04
  name: frontend-wl04
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-wl04
  template:
    metadata:
      labels:
        app: frontend-wl04
    spec:
      containers:
      - image: kodekloud/webapp-color:v1
        name: simple-webapp
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-wl04-svc
  name: frontend-wl04-svc
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: frontend-wl04
  type: NodePort

