apiVersion: v1
kind: Pod
metadata:
  name: frontend-stable-cka05-arch
spec:
  containers:
  - name: fe-cka05-arch
    image: vish/stress
    resources:
      limits:
        cpu: "0.3"
      requests:
        cpu: "0.2"
    args:
    - -cpus
    - "1"
