---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-wl06
  name: nginx-wl06
spec:
  containers:
  - image: nginx
    name: nginx-wl06
    resources:
      requests:
        memory: 100Gi
        
